### ISSUE TITLE
Is there a way to load the breakout project in Kicad?

### ISSUE THREAD

**Issue by alex3331** [apoloval/msx-cartridge#4]
Unable to load. because .sch file is shown as not valid.

**Comment by apoloval** [comment]
What version of KiCAD are you using? This project was generated with KiCAD 6. 

I am progressively migrating the rest of projects to that version. My recommendation is to update if you didn't yet.

**Comment by apoloval** [comment]
I hope my last comment answered your question. Please feel free to reopen the issue otherwise.
