### ISSUE TITLE
64kb?

### ISSUE THREAD

**Issue by elosha** [apoloval/msx-cartridge#5]
From readme.md:
> It will fit any ROM dump <64kb.

I guess this should either be 64 KB (KByte) or 512 Kb (Kbit) – right? Sorry for asking, in ROM context both makes sense.

**Comment by apoloval** [comment]
Exactly. `kb` refers to kibibytes (1024 bytes).

**Comment by apoloval** [comment]
I hope my last comment answered your question. Please feel free to reopen the issue otherwise.
