### ISSUE TITLE
Less than 64KB on 64KB cartridge PCB

### ISSUE THREAD

**Issue by elosha** [apoloval/msx-cartridge#6]
_Edit: Nevermind, it seems I've ordered an old revision with 27C512 back then … but still interested to learn ;)_

I've already ordered your 64KB cartridge PCBs, but seeing other cartridge PCBs made me suspicious.

1. They require setting jumpers in order to use a 512Kbit ROM because of memory mapping, and other jumpers to use smaller ROMs because of different pinouts. Your layout even suggests a SST39SF010 and stays completely jumperless. How does memory mapping work?

Additionally, I've still got smaller EPROMs available. You wrote that ROMs with less than 64K are ok. Questions regarding replacing the SST39SF010, since pinouts are incompatible:

2. Is it correct that disconnecting pin `#30 NC` (≙ `#28 Vcc` on a DIP28 footprint) from the circuit and connecting it to _Vcc_ instead (making it a supply pin) simply allows using a 27C512, if aligned to the right?
3. Going further, connecting `#3 A15` (≙ `#1 Vpp` on DIP28) to _GND_ and `#29 A14` (≙ `#27 /PGM` on DIP28) to _Vcc_ instead would allow to fit a 27C256? But would it work in MSX memory mapping context?

**Comment by apoloval** [comment]
There is no selectable memory mapping in this design. The first 64KBs of ROM memory are mapped to the 64KB memory space of the cartridge slot. The rest of ROM memory is not mapped. This is the simplest design ever possible for a ROM cartridge.

This was designed with the SST39SF0x0 chip in mind. For other ROM chips that use a different pinout, connections should be rewired accordingly, yes.

**Comment by apoloval** [comment]
I hope my last comment answered your question. Please feel free to reopen the issue otherwise.
